"""Emit a merged vocabulary.yaml — current file plus staged admin decisions.

Decisions are STAGED, not applied. The source of truth is a file in git; the
generated output is downloaded, committed, reviewed in a PR, and deployed. A
live ConfigMap mutation would be lost on the next deploy and would make the
database a second, divergent source of truth.
"""

from __future__ import annotations

from importlib.resources import files as _pkg_files
from typing import Any

import yaml

from rcars.services.vocabulary.models import DIMENSIONS, Vocabulary

_GENERATED_BANNER = (
    "# ─────────────────────────────────────────────────────────────────────────\n"
    "# GENERATED by the RCARS admin vocabulary page (RHDPCD-507).\n"
    "# Review, commit, open a PR, and deploy. Takes effect on the next rollout.\n"
    "# ─────────────────────────────────────────────────────────────────────────\n"
)


def _header_comment() -> str:
    """Preserve the packaged file's leading comment block."""
    path = _pkg_files("rcars.data").joinpath("vocabulary.yaml")
    lines: list[str] = []
    for line in path.read_text().splitlines():
        if line.startswith("#") or not line.strip():
            lines.append(line)
        else:
            break
    return "\n".join(lines).rstrip() + "\n\n"


def _entries_to_dicts(vocab: Vocabulary, dimension: str) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for entry in vocab.entries(dimension):
        item: dict[str, Any] = {"name": entry.name, "aliases": list(entry.aliases)}
        if entry.search_terms:
            item["search_terms"] = list(entry.search_terms)
        if entry.is_tdp:
            item["is_tdp"] = True
        out.append(item)
    return out


def generate_vocabulary_yaml(vocab: Vocabulary, decisions: list[dict[str, Any]]) -> str:
    """Merge staged decisions into the loaded vocabulary and serialize.

    aliased  → term appended to the target entry's aliases
    promoted → term becomes a new canonical entry in that dimension
    rejected → term appended to ignored_terms[dimension]
    pending  → ignored
    """
    data: dict[str, Any] = {d: _entries_to_dicts(vocab, d) for d in DIMENSIONS}
    ignored: dict[str, list[str]] = {
        d: sorted(vocab.ignored_originals.get(d, ())) for d in DIMENSIONS
    }

    for decision in decisions:
        dimension = decision.get("dimension")
        term = (decision.get("term") or "").strip()
        status = decision.get("status")
        if dimension not in data or not term:
            continue

        if status == "aliased":
            target = decision.get("resolved_to")
            for entry in data[dimension]:
                if entry["name"] == target:
                    if term not in entry["aliases"]:
                        entry["aliases"].append(term)
                    break
        elif status == "promoted":
            if not any(e["name"] == term for e in data[dimension]):
                data[dimension].append({"name": term, "aliases": []})
        elif status == "rejected":
            if term not in ignored[dimension]:
                ignored[dimension].append(term)
                ignored[dimension].sort()

    data["action_verbs"] = {
        mode: {"valid": list(lists.get("valid", ())), "rejected": list(lists.get("rejected", ()))}
        for mode, lists in vocab.action_verbs.items()
    }
    data["content_modes"] = dict(vocab.content_modes)
    data["ignored_terms"] = ignored

    body = yaml.safe_dump(data, sort_keys=False, default_flow_style=False, allow_unicode=True)
    return _header_comment() + _GENERATED_BANNER + "\n" + body
