---
- name: Render manifests template
  ansible.builtin.template:
    src: manifests.yaml.j2
    dest: "/tmp/rcars-{{ env }}-manifests.yaml"
  changed_when: false

- name: Apply rendered manifests
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ target_namespace }}"
    src: "/tmp/rcars-{{ env }}-manifests.yaml"
    state: present
    apply: true

- name: Clean up rendered manifests
  ansible.builtin.file:
    path: "/tmp/rcars-{{ env }}-manifests.yaml"
    state: absent
  changed_when: false
