---
- name: Start build for {{ app_name }} and wait for completion
  ansible.builtin.command:
    cmd: >-
      oc start-build {{ app_name }}
      -n {{ target_namespace }}
      --follow
      --wait
      --kubeconfig={{ kubeconfig | expanduser }}
  changed_when: true

- name: Rollout restart {{ app_name }} deployment
  ansible.builtin.command:
    cmd: >-
      oc rollout restart deployment/{{ app_name }}
      -n {{ target_namespace }}
      --kubeconfig={{ kubeconfig | expanduser }}
  changed_when: true

- name: Wait for {{ app_name }} rollout to complete
  ansible.builtin.command:
    cmd: >-
      oc rollout status deployment/{{ app_name }}
      -n {{ target_namespace }}
      --kubeconfig={{ kubeconfig | expanduser }}
      --timeout=120s
  changed_when: false
